---
- name: Get Node Exporter binaries
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    checksum: "sha256:{{ node_exporter_checksum }}"

- name: Extract Node Exporter binaries
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "{{ prometheus_binary_dir }}/exporters/"
    creates: "{{ prometheus_binary_dir }}/exporters/node_exporter-{{ node_exporter_version }}.linux-amd64"
    remote_src: true

- name: Install Node Exporter service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  become: true
  notify:
    - Restart Prometheus

- name: Ensure Node Exporter service is started and enabled
  ansible.builtin.systemd:
    daemon_reload: true
    name: node_exporter
    state: started
    enabled: true
  become: true